version: "2"
services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    command: yarn run start
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - ./shared:/shared
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    command: yarn run watch
    ports:
      - "3100:3100"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_DATABASE_TESTING=${MYSQL_DATABASE_TESTING}
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./server:/server
      - ./shared:/shared
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    expose: 
      - "80"
    volumes:
      - /sessions
    depends_on:
      - "mysql"

volumes:
  mysqldata:
    driver: "local"